{% set name = "mdf_forge" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14d7e9c0c8edc2232379ad4175b95aac9cab4afca50ec8e699617bbc174e5400

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pip
    - mdf_toolbox >=0.4.10
    - globus-sdk >=1.7.0
    - requests >=2.18.4
    - tqdm >=4.19.4

test:
  imports:
    - mdf_forge
  commands:
    - pip check

about:
  home: https://github.com/materials-data-facility/forge
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Forge is the Python package to access data in the Materials Data Facility

  description: |
    Forge is the Materials Data Facility Python package to interface and 
    leverage the MDF Data Discovery service. Forge allows users to perform 
    simple queries and facilitiates moving and synthesizing results.
  doc_url: http://mdf-forge.readthedocs.io/
  dev_url: https://github.com/materials-data-facility/forge

extra:
  recipe-maintainers:
    - jan-janssen
