{% set name = "mdf_forge" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5489051412dddb513cc21b9ca70cd11849f684e37a510789ed870ce6e5f17daa

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pip
    - mdf_toolbox >=0.4.10
    - globus-sdk >=1.7.0
    - requests >=2.18.4
    - tqdm >=4.19.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - mdf_forge
  commands:
    - pip check

about:
  home: https://github.com/materials-data-facility/forge
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Forge is the Python package to access data in the Materials Data Facility

  description: |
    Forge is the Materials Data Facility Python package to interface and 
    leverage the MDF Data Discovery service. Forge allows users to perform 
    simple queries and facilitiates moving and synthesizing results.
  doc_url: http://mdf-forge.readthedocs.io/
  dev_url: https://github.com/materials-data-facility/forge

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
