{% set name = "mdf_forge" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97c303a67bfda36919eba66e43dd1afc9a1060b4d1d6e6841abab9f9c0b07b5f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - mdf_toolbox >=0.4.10
    - globus-sdk >=1.7.0
    - requests >=2.18.4
    - tqdm >=4.19.4

test:
  imports:
    - mdf_forge
  commands:
    - pip check

about:
  home: https://github.com/materials-data-facility/forge
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Forge is the Python package to access data in the Materials Data Facility'

  description: |
    Forge is the Materials Data Facility Python package to interface and 
    leverage the MDF Data Discovery service. Forge allows users to perform 
    simple queries and facilitiates moving and synthesizing results.
  doc_url: http://mdf-forge.readthedocs.io/
  dev_url: https://github.com/materials-data-facility/forge

extra:
  recipe-maintainers:
    - jan-janssen
