travis:
  secure:
    BINSTAR_TOKEN: HC91xtllGkkBDEnkSaoLugR7hTtONhtlp9GumC3v4nb0Q1K2Bx+jeFlwJNfCOVjOgPzX5ZT4HH8hchhMlwOhxpA87cQ4eyYH9iOREarlVCjm984HHt/DBCR8i7iU95D1gqL5MQA6jitYizXwmXm+YVZ1vRjvPoAFtSlqgfj0dpX3jJI3SbtGcNIwHsU/sgBu/UnJDoogVSPmbNC7R/stsJzRl7pkZ/85rOjSX5npHVG+m1QcxjXc3NTCZ8ushhxhfIEcqy3ZY50RaVXTDKR3+nbq2dcCTDYZhkpzQ/9XDvhrOwoXFmqPotfkskFYu52hlkhmBQ6HQ9k+tXCq/nGtqsZz+bvTG8Q8Cc+m4cpElnhq1xpGBQm17Z0LqueBcSzvLVahWiQlll6ua51b+SUJqCZFYj5xcVOWBLLUQsvvjUAQ+NoM8pbYciGWKJYwSkDMLDZlOIE7Pw7/23mInhYNydOr0lPys1C7rw+hvQM9DmcOcGl/7lP7e3uDEvOsrd7Rg9Kt1CcTcR6Tsv+kHPTlGVDgEIecA4Ln8SjV91l/sRe2n7SWG/Pd3Kcsij6xun9bkPoPWYJGjQroRH09/cLMglnZddRVEsaiUyd8NGXd8sssCkz5ex9NLP0OB/qfwVLTlhZa7UTK4WkEf3TNR2vdlR4STmReb0cYcTU4Cff4d9A=
bot:
  automerge: true
conda_forge_output_validation: true
